/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package jokenpo;

/**
 *
 * @author peixa_000
 */
public class GUI_telaInicial extends javax.swing.JFrame {

    /**
     * Creates new form GUI_telaInicial
     */
    public GUI_telaInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JLtitulo = new javax.swing.JLabel();
        JLimgTitulo = new javax.swing.JLabel();
        Jdesktop = new javax.swing.JDesktopPane();
        JLapresentacao = new javax.swing.JLabel();
        JBopcao1 = new javax.swing.JButton();
        JBopcao2 = new javax.swing.JButton();
        JBopcao3 = new javax.swing.JButton();
        JBopcao4 = new javax.swing.JButton();
        JBsair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOKENPÔ");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 51, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JLtitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JLtitulo.setForeground(new java.awt.Color(255, 255, 255));
        JLtitulo.setText("JOKENPÔ");

        JLimgTitulo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/logoTitulo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JLimgTitulo)
                .addGap(121, 121, 121)
                .addComponent(JLtitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLimgTitulo)
                    .addComponent(JLtitulo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JLapresentacao.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JLapresentacao.setText("Escolha um modo de jogo:");

        JBopcao1.setBackground(new java.awt.Color(0, 51, 255));
        JBopcao1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBopcao1.setForeground(new java.awt.Color(255, 255, 255));
        JBopcao1.setText("1 Partida");
        JBopcao1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBopcao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBopcao1ActionPerformed(evt);
            }
        });

        JBopcao2.setBackground(new java.awt.Color(0, 51, 255));
        JBopcao2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBopcao2.setForeground(new java.awt.Color(255, 255, 255));
        JBopcao2.setText("3 Partidas");
        JBopcao2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBopcao3.setBackground(new java.awt.Color(0, 51, 255));
        JBopcao3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBopcao3.setForeground(new java.awt.Color(255, 255, 255));
        JBopcao3.setText("5 Partidas");
        JBopcao3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBopcao4.setBackground(new java.awt.Color(0, 51, 255));
        JBopcao4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBopcao4.setForeground(new java.awt.Color(255, 255, 255));
        JBopcao4.setText("7 Partidas");
        JBopcao4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JBsair.setBackground(new java.awt.Color(0, 51, 255));
        JBsair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        JBsair.setForeground(new java.awt.Color(255, 255, 255));
        JBsair.setText("Sair");
        JBsair.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsairActionPerformed(evt);
            }
        });

        Jdesktop.setLayer(JLapresentacao, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jdesktop.setLayer(JBopcao1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jdesktop.setLayer(JBopcao2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jdesktop.setLayer(JBopcao3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jdesktop.setLayer(JBopcao4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Jdesktop.setLayer(JBsair, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout JdesktopLayout = new javax.swing.GroupLayout(Jdesktop);
        Jdesktop.setLayout(JdesktopLayout);
        JdesktopLayout.setHorizontalGroup(
            JdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JdesktopLayout.createSequentialGroup()
                .addGroup(JdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JdesktopLayout.createSequentialGroup()
                        .addGroup(JdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JdesktopLayout.createSequentialGroup()
                                .addGap(129, 129, 129)
                                .addComponent(JLapresentacao))
                            .addGroup(JdesktopLayout.createSequentialGroup()
                                .addGap(174, 174, 174)
                                .addGroup(JdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JBopcao4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBopcao2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBopcao3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(JBopcao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 137, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JdesktopLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(JBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JdesktopLayout.setVerticalGroup(
            JdesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JdesktopLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JLapresentacao)
                .addGap(18, 18, 18)
                .addComponent(JBopcao1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBopcao2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBopcao3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JBopcao4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(JBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Jdesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Jdesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void JBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_JBsairActionPerformed

    private void JBopcao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBopcao1ActionPerformed
        // TODO add your handling code here:
        GUI_opcao1 tela1 = new GUI_opcao1();
        Jdesktop.add(tela1);
        tela1.setVisible(true);
    }//GEN-LAST:event_JBopcao1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_telaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_telaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBopcao1;
    private javax.swing.JButton JBopcao2;
    private javax.swing.JButton JBopcao3;
    private javax.swing.JButton JBopcao4;
    private javax.swing.JButton JBsair;
    private javax.swing.JLabel JLapresentacao;
    private javax.swing.JLabel JLimgTitulo;
    private javax.swing.JLabel JLtitulo;
    private javax.swing.JDesktopPane Jdesktop;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
