/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package notasponderadas_2gti;

import java.awt.Color;

/**
 *
 * @author Professor
 */
public class GUI_NotasPonderadas extends javax.swing.JFrame {

    /**
     * Creates new form GUI_NotasPonderadas
     */
    public GUI_NotasPonderadas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Habilitados = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jcb_Nota1 = new javax.swing.JCheckBox();
        jcb_Nota2 = new javax.swing.JCheckBox();
        jcb_Nota3 = new javax.swing.JCheckBox();
        jcb_Nota4 = new javax.swing.JCheckBox();
        jcb_Nota5 = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jtf_Nota1 = new javax.swing.JTextField();
        jtf_Nota2 = new javax.swing.JTextField();
        jtf_Nota3 = new javax.swing.JTextField();
        jtf_Nota4 = new javax.swing.JTextField();
        jtf_Nota5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jtf_Peso1 = new javax.swing.JTextField();
        jtf_Peso2 = new javax.swing.JTextField();
        jtf_Peso3 = new javax.swing.JTextField();
        jtf_Peso4 = new javax.swing.JTextField();
        jtf_Peso5 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jtf_Media = new javax.swing.JTextField();
        jtf_SomaDosPesos = new javax.swing.JTextField();
        jb_Sair = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jb_Calcular = new javax.swing.JButton();
        jb_VerificarPeso = new javax.swing.JButton();
        jb_Limpar = new javax.swing.JButton();
        jcb_MediaComPesos = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setText("Sistema de Notas Ponderadas");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Kauan Ferreira Lemos");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("RA: 17.127");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(161, 161, 161))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Habilitados.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Habilitados.setRequestFocusEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Habilitado");

        jcb_Nota1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_Nota1.setText("Nota1");
        jcb_Nota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_Nota1ActionPerformed(evt);
            }
        });

        jcb_Nota2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_Nota2.setText("Nota 2");

        jcb_Nota3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_Nota3.setText("Nota 3");

        jcb_Nota4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_Nota4.setText("Nota 4");

        jcb_Nota5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_Nota5.setText("Nota 5");

        javax.swing.GroupLayout HabilitadosLayout = new javax.swing.GroupLayout(Habilitados);
        Habilitados.setLayout(HabilitadosLayout);
        HabilitadosLayout.setHorizontalGroup(
            HabilitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HabilitadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(HabilitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(HabilitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jcb_Nota2)
                        .addComponent(jcb_Nota3)
                        .addComponent(jcb_Nota4)
                        .addComponent(jcb_Nota5)
                        .addComponent(jcb_Nota1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        HabilitadosLayout.setVerticalGroup(
            HabilitadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HabilitadosLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jcb_Nota1)
                .addGap(18, 18, 18)
                .addComponent(jcb_Nota2)
                .addGap(18, 18, 18)
                .addComponent(jcb_Nota3)
                .addGap(18, 18, 18)
                .addComponent(jcb_Nota4)
                .addGap(18, 18, 18)
                .addComponent(jcb_Nota5)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setPreferredSize(new java.awt.Dimension(159, 336));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Notas");

        jtf_Nota1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Nota1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtf_Nota5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Nota4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Nota3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Nota2, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Nota4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jtf_Nota5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setPreferredSize(new java.awt.Dimension(159, 336));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Pesos");

        jtf_Peso1.setText("0");
        jtf_Peso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Peso1ActionPerformed(evt);
            }
        });

        jtf_Peso2.setText("0");
        jtf_Peso2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Peso2ActionPerformed(evt);
            }
        });

        jtf_Peso3.setText("0");

        jtf_Peso4.setText("0");
        jtf_Peso4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_Peso4ActionPerformed(evt);
            }
        });

        jtf_Peso5.setText("0");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtf_Peso1, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                            .addComponent(jtf_Peso2)
                            .addComponent(jtf_Peso3)
                            .addComponent(jtf_Peso4)
                            .addComponent(jtf_Peso5))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jtf_Peso5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Média =");

        jtf_Media.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_MediaActionPerformed(evt);
            }
        });

        jb_Sair.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_Sair.setText("Sair");
        jb_Sair.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(102, 102, 102)
                .addComponent(jtf_Media, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addComponent(jtf_SomaDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_Media, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtf_SomaDosPesos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jb_Sair, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jb_Calcular.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_Calcular.setText("CALCULAR");
        jb_Calcular.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_Calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_CalcularActionPerformed(evt);
            }
        });

        jb_VerificarPeso.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_VerificarPeso.setText("VERIFICAR PESOS");
        jb_VerificarPeso.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_VerificarPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_VerificarPesoActionPerformed(evt);
            }
        });

        jb_Limpar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jb_Limpar.setText("LIMPAR");
        jb_Limpar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jb_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_LimparActionPerformed(evt);
            }
        });

        jcb_MediaComPesos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jcb_MediaComPesos.setText("Média Com Pesos");
        jcb_MediaComPesos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_MediaComPesosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jb_VerificarPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 239, Short.MAX_VALUE)
                        .addComponent(jb_Calcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jb_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jcb_MediaComPesos, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jcb_MediaComPesos)
                .addGap(18, 18, 18)
                .addComponent(jb_VerificarPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Calcular, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jb_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Habilitados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(Habilitados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 323, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_Peso4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Peso4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Peso4ActionPerformed

    private void jb_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_LimparActionPerformed
      //Limpar o modelo matematico 
        cnp.Limpar();
       //Limpar a interface grafica
       jtf_Nota1.setText(" ");
       jtf_Nota2.setText(" ");
       jtf_Nota3.setText(" ");
       jtf_Nota4.setText(" ");
       jtf_Nota5.setText(" ");
       jtf_Peso1.setText(" ");
       jtf_Peso2.setText(" ");
       jtf_Peso3.setText(" ");
       jtf_Peso4.setText(" ");
       jtf_Peso5.setText(" ");
       jtf_Media.setText(" ");
       jtf_SomaDosPesos.setText(" ");
       jcb_Nota1.setSelected(false);
       jcb_Nota2.setSelected(false);
       jcb_Nota3.setSelected(false);
       jcb_Nota4.setSelected(false);
       jcb_Nota5.setSelected(false);
       jcb_MediaComPesos.setSelected(false);
      
    }//GEN-LAST:event_jb_LimparActionPerformed

    private void jb_CalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_CalcularActionPerformed
      cnp.setNota1(   Double.parseDouble(jtf_Nota1.getText()));
       //Pega o valor em forma de texto da interface e transforma em double
      cnp.setNota2(   Double.parseDouble(jtf_Nota2.getText()));
      cnp.setNota3(   Double.parseDouble(jtf_Nota3.getText()));
      cnp.setNota4(   Double.parseDouble(jtf_Nota4.getText()));
      cnp.setNota5(   Double.parseDouble(jtf_Nota5.getText()));
    
      //verificar se o calculo e ponderado
      if (cnp.isNotasPonderadas() == true){
      cnp.setPeso1(   Double.parseDouble(jtf_Peso1.getText()));
      cnp.setPeso2(   Double.parseDouble(jtf_Peso2.getText()));
      cnp.setPeso3(   Double.parseDouble(jtf_Peso3.getText()));
      cnp.setPeso4(   Double.parseDouble(jtf_Peso4.getText()));
      cnp.setPeso5(   Double.parseDouble(jtf_Peso5.getText()));

      }
      //Falta arrumar essa linha
     // if(cnp.setNota1(" ")){ jtf_Nota1.;}
      cnp.calcularMedia();
      jtf_Media.setText(String.valueOf(cnp.getMedia()));

    }//GEN-LAST:event_jb_CalcularActionPerformed

    private void jtf_Peso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Peso1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Peso1ActionPerformed

    private void jtf_Peso2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Peso2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Peso2ActionPerformed

    private void jcb_MediaComPesosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_MediaComPesosActionPerformed
        if(jcb_MediaComPesos.isSelected() == true){
            cnp.setNotasPonderadas(true);
            jcb_MediaComPesos.setSelected(true);
                    } else { 
             cnp.setNotasPonderadas(false);
            jcb_MediaComPesos.setSelected(false);
        }
    }//GEN-LAST:event_jcb_MediaComPesosActionPerformed

    private void jb_VerificarPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_VerificarPesoActionPerformed
       double soma10;
       cnp.setPeso1(Double.parseDouble(jtf_Peso1.getText()));
       cnp.setPeso2(Double.parseDouble(jtf_Peso2.getText()));
       cnp.setPeso3(Double.parseDouble(jtf_Peso3.getText()));
       cnp.setPeso4(Double.parseDouble(jtf_Peso4.getText()));
       cnp.setPeso5(Double.parseDouble(jtf_Peso5.getText()));
       soma10 = cnp.getPeso1() +  cnp.getPeso2() + cnp.getPeso3() + cnp.getPeso4() + cnp.getPeso5();
       if(soma10 != 10){
        jtf_SomaDosPesos.setBackground(Color.red);
        jtf_SomaDosPesos.setForeground(Color.black);
       } else {jtf_SomaDosPesos.setBackground(Color.green); }
       jtf_SomaDosPesos.setText(String.valueOf(soma10));
    }//GEN-LAST:event_jb_VerificarPesoActionPerformed

    private void jtf_Nota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_Nota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_Nota1ActionPerformed

    private void jcb_Nota1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_Nota1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_Nota1ActionPerformed

    private void jtf_MediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_MediaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_MediaActionPerformed

    private void jb_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_SairActionPerformed
    dispose();
    }//GEN-LAST:event_jb_SairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_NotasPonderadas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_NotasPonderadas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Habilitados;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton jb_Calcular;
    private javax.swing.JButton jb_Limpar;
    private javax.swing.JButton jb_Sair;
    private javax.swing.JButton jb_VerificarPeso;
    private javax.swing.JCheckBox jcb_MediaComPesos;
    private javax.swing.JCheckBox jcb_Nota1;
    private javax.swing.JCheckBox jcb_Nota2;
    private javax.swing.JCheckBox jcb_Nota3;
    private javax.swing.JCheckBox jcb_Nota4;
    private javax.swing.JCheckBox jcb_Nota5;
    private javax.swing.JTextField jtf_Media;
    private javax.swing.JTextField jtf_Nota1;
    private javax.swing.JTextField jtf_Nota2;
    private javax.swing.JTextField jtf_Nota3;
    private javax.swing.JTextField jtf_Nota4;
    private javax.swing.JTextField jtf_Nota5;
    private javax.swing.JTextField jtf_Peso1;
    private javax.swing.JTextField jtf_Peso2;
    private javax.swing.JTextField jtf_Peso3;
    private javax.swing.JTextField jtf_Peso4;
    private javax.swing.JTextField jtf_Peso5;
    private javax.swing.JTextField jtf_SomaDosPesos;
    // End of variables declaration//GEN-END:variables
CalcularNotasPonderadas cnp = new CalcularNotasPonderadas();
}
